name: pocketbase
description: Multi-platform Dart SDK for PocketBase, an open source realtime backend in 1 file.
repository: https://github.com/pocketbase/dart-sdk

version: 0.19.0-rc4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.0.0
  lints: ^4.0.0
  test: ^1.16.0
