name: pocketbase
description: Multi-platform Dart SDK for PocketBase, an open source realtime backend in 1 file.
repository: https://github.com/pocketbase/dart-sdk

version: 0.10.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  http: ^0.13.4
  json_annotation: ^4.2.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.0.0
  lints: ^2.0.0
  test: ^1.16.0
